### PR TITLE
NAS-132624 / 25.04 / Add Silver International

### PR DESCRIPTION
**Pull request by william-gr**

### CODE REVIEW

**Comment by william-gr** [comment]
Might want to merge this only after branching out .1?

**Review by yocalebo — CHANGES_REQUESTED** [review]
I thought you already merged this to `master`?

**Comment by william-gr** [comment]
Err, yes, wrong branch

**Comment by william-gr** [comment]
backport

**Comment by william-gr** [comment]
backport

**Comment by william-gr** [comment]
backport

**Comment by william-gr** [comment]
backport

**Pull request closed without merging**
